### ISSUE TITLE
1/3 Frequency

### ISSUE THREAD

**Issue by marc-gist** [timsavage/fg100alt-firmware#1]
For some reason (and it could be that I'm a noob with OScopes) my scope shows 1/3 the frequency when using the stock firmware and yours.

Yet when I connect to the internal 1kHz it shows the correct value.
I have a SIGLENT SDS1102CML

Thanks,

**Comment by marc-gist** [comment]
Seems its a hardware issue (i'm guessing) on the fg100, as using an arduino with tone(2, 1000), I get my 1kHz reading (well, close enough anyways, 997.something Hz).
Any ideas where to look to fix this issue?

**Comment by timsavage** [comment]
That does sound like a possible hardware fault. First thing to check is the frequency of the clock crystal on the FG100. All the units I've seen use a 30Mhz crystal but if all your measurements are 1/3 of the defined frequency your unit may have a 10Mhz crystal installed.

If this is indeed that case change the _CLK_FREQ_ variable in the Makefile with the value of your crystal (for a 10Mhz crystal this would be 10000000UL) and rebuild the firmware with: `make clean install`

The downside of have a slower crystal is that it will limit the highest frequency that the unit will be able to generate, however it is a simple job to replace the crystal with a known 30Mhz part.

**Comment by timsavage** [comment]
No response. Closing...
