### ISSUE TITLE
Increasing/Decreasing frequency while running

### ISSUE THREAD

**Issue by ramast** [timsavage/fg100alt-firmware#3]
This alter firmware certainly has more improvements over the original, I even feel the generated waves are cleaner.

One missing feature however is ability to increase/decrease frequency on the fly (while it's running).
I checked the code and I can see that signal generation is done in a continuous assembly loop to guarantee maximum speed possible and I think it only stops with an interrupt triggered by pressing the run button.

My question is, can we setup another interrupt for the + and - buttons so when pressed we exit the loop, increase/decrease frequency then resume the loop again?
From user perspective, it would seem as if the signal has never stopped.

**Comment by timsavage** [comment]
The loop as tuned to provide the correct frequency (in all of the calculations the clock rate and the number of clock cycles in the DDS loop is used). Adding in any additional delays into that loop causes an interupt in the DDS output, on a scope this is seen as a platue in the waveform. 

Changing the frequency on the fly requires quite a large number of cycles, handling of the interrupt, calculation of the new frequency and updating the display, in practice that would cause a large blip on a scope, and would be audible if generating audio frequencies.

I have been working on a successor to this project that utilises two micros, one for DDS and a second for the display and calculations. Although even in this situation there is some distortion on change (especially when sweeping through frequencies.

**Comment by ramast** [comment]
I understand that wave generation is very time sensitive and can't possibility take any delays to check for user input.

this however was not my suggestion at all.
My suggestion was using arduino's pin change intrrupt.
https://thewanderingengineer.com/2014/08/11/arduino-pin-change-interrupts/

Basically we ask arduino to inform us when status of pins corresponding to the Plus and Minus buttons has changed.
So long as you didn't press these buttons, no code will be executed and there will be no delay.
Once you press one of these buttons, your interrupt routine will be automatically called.
Inside that routine we can turn off wave generation, analyze user's input [i.e which button was pressed], update frequency accordingly then resume wave generation.

**Comment by timsavage** [comment]
Firstly this project is built with AVR libc and does not use Arduino. The Arduino environment is not really suitable for this use-case.

Unfortunately what you are proposing does not work with the hardware. All buttons (except run/stop) are part of a button matrix that needs to be scanned to determine which button is pressed, see the `operator_input` method of `main.c`.

However, even if we could use interrupts, then the process of stopping generation, recalculating etc causes distortions in the output. Users would expect that pressing the +/- buttons would change the frequency smoothly, multiple presses will produce an even more garbled waveform which intern affects the output frequency. Even worse hardware does not include any debounce, this is done in software, a 5ms settling delay used to debounce buttons equates to ~166,666 cycles through the DDS loop (based on a 30MHz clock frequency @ 9 clocks per loop).
